// Code generated by "stringer -type=TypeOf"; DO NOT EDIT.

package types

import "strconv"

const _Kind_name = "KindNameKindPointerKindArrayKindMapKindInterfaceKindImportKindEllipsisKindChanKindFunc"

var _Kind_index = [...]uint8{0, 8, 19, 28, 35, 48, 58, 70, 78, 86}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "TypeOf(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
