// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package types

import "strconv"

const _Kind_name = "KindNameKindPointerKindArrayKindMapKindInterfaceKindImportKindEllipsisKindChanKindFuncKindStruct"

var _Kind_index = [...]uint8{0, 8, 19, 28, 35, 48, 58, 70, 78, 86, 96}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
